# Generated by Django 2.2.10 on 2020-04-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200412_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategories',
            name='is_active',
            field=models.BooleanField(default=0, verbose_name='Статус'),
        ),
    ]
