# Generated by Django 2.2.10 on 2020-05-09 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200508_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес страницы'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='locale',
            field=models.CharField(blank=True, choices=[('RU', 'RU'), ('EN', 'EN')], max_length=2, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 12, 24, 17, 578837, tzinfo=utc), verbose_name='Время жизни ключа'),
        ),
    ]
