# Generated by Django 2.2.10 on 2020-05-09 14:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20200509_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 14, 47, 43, 506433, tzinfo=utc), verbose_name='Время жизни ключа'),
        ),
    ]
