# Generated by Django 2.2.10 on 2020-05-09 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20200509_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='tagline',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 14, 51, 24, 553072, tzinfo=utc), verbose_name='Время жизни ключа'),
        ),
    ]
