# Generated by Django 2.2.10 on 2020-05-12 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20200509_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 16, 0, 50, 666993, tzinfo=utc), verbose_name='Время жизни ключа'),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='locale',
            field=models.CharField(blank=True, choices=[('ru', 'RU'), ('en', 'EN')], max_length=2, verbose_name='Язык'),
        ),
    ]
