# Generated by Django 2.2.10 on 2020-05-15 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_products_is_active'),
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Orders',
        ),
        migrations.RenameModel(
            old_name='OrderProducts',
            new_name='OrdersProducts',
        ),
        migrations.RenameModel(
            old_name='OrderUserInfo',
            new_name='OrdersUserInfo',
        ),
    ]
